name: "Policyer GitHub Action"
author: "Nir Adler"
description: "Run Policyer as github action"

inputs:
  checks_path:
    description: "checks directory path"
    default: "./checks"
    required: false
  format:
    description: "output format"
    required: false
  output_path:
    description: "output path"
    required: false
  fail_on:
    description: "fail on"
    required: false
  fail_on_vale:
    description: "fail on value"
    required: false
  filter:
    description: "filter"
    required: false
  filter_flags:
    description: "filter flags"
    required: false
  internal:
    description: "use internal checks"
    required: false
  verbose:
    description: "enable debug logs"
    required: false
  provider:
    description: "provider npm package name"
    default: "policyer"
    required: false
  github_token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
    required: false
    default: ${{ github.token }}

outputs:
  results:
    description: "Run results"

branding:
  icon: "anchor"
  color: "blue"

runs:
  using: "docker"
  image: "docker://niradler/policyer:latest"
  args:
    - ${{ inputs.checks_path }}
    - ${{ inputs.format }}
    - ${{ inputs.output_path }}
    - ${{ inputs.fail_on }}
    - ${{ inputs.fail_on_vale }}
    - ${{ inputs.filter }}
    - ${{ inputs.filter_flags }}
    - ${{ inputs.internal }}
    - ${{ inputs.verbose }}
    - ${{ inputs.provider }}
    - ${{ inputs.github_token }}
